### ISSUE TITLE
Error loading LTN with Amator Phasma's Mods (forked), Angels, Bobs and Clowns

### ISSUE THREAD

**Issue by szentigrad3** [Yousei9/Logistic-Train-Network#306] opened 2022-09-25 10:03 UTC
https://i.imgur.com/HZF9jIG.png

**Comment by Yousei9** [comment] 2022-09-25 10:19
Duplicate of #303 
LTN + APM work fine so another mod messes the prototypes up.

**Closed by Yousei9** 2022-09-25 10:19 UTC
Labels: bug
