### ISSUE TITLE
Request: Change default network to 1 instead of -1

### ISSUE THREAD

**Issue by wesdotcool** [Yousei9/Logistic-Train-Network#264] opened 2021-05-11 20:54 UTC
If you don't set an encoded network id on the train stop combinator, then it defaults to all 32 possible networks. When you're new and getting your base started this works just fine. But if you later decide that you want separate networks, you now have to go back and change the train stop combinator station you have created so that you can have 2 separate train stops. Additionally, if you're in a multiplayer game and you have different networks, other players often place down train stops and use the default settings, which will place those new train stops on those specialized networks.

If 1 was the default, then the other 31 networks could be used at any time with no changes to your existing "default" system, and you're less likely to mess anything up by accidentally using the default settings.

**Comment by Yousei9** [comment] 2021-05-12 14:53
Duplicate of already implemented request #163

**Closed by Yousei9** 2021-05-12 14:53 UTC
