### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by moatra** [Yousei9/Logistic-Train-Network#88] opened 2017-12-27 07:47 UTC
Map Version:  0.16.7-4
Mods:
* LogisticTrainNetwork 1.6.1
* base 0.16.7
* creative-mode-fix 0.0.9

Opening the map (attached) results in a migration error:

```
Error while running on_configuration_changed: Passed index is out of range.
stack traceback:
	__LogisticTrainNetwork__/control.lua:1746: in function 'getWagonCapacity'
	__LogisticTrainNetwork__/control.lua:1761: in function 'GetTrainCapacity'
	__LogisticTrainNetwork__/control.lua:219: in function 'updateEntities'
	__LogisticTrainNetwork__/control.lua:287: in function <__LogisticTrainNetwork__/control.lua:271>
```
[Planning Small 16.zip](https://github.com/Yousei9/Logistic-Train-Network/files/1588570/Planning.Small.16.zip)

**Comment by Yousei9** [comment] 2017-12-27 10:11
duplicate of #86 
use 0.16.6 until 0.16.8 fixed the api

**Closed by Yousei9** 2017-12-27 10:11 UTC
