### ISSUE TITLE
LTN crashes Factorio when a timed out delivery arrives at the station

### ISSUE THREAD

**Issue by tomribbens** [Yousei9/Logistic-Train-Network#227] opened 2020-08-28 13:39 UTC
So I had a train run out of fuel, and by the time I got to it, the delivery in LTN timed out. When I then simply fuel up the train, the game crashes the moment the train arrives at it's station where it will unload the goods. It crashes with the following error message:

The mod LTN - Logistic Train Network (1.14.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_train_changed_state (ID 23)
__LogisticTrainNetwork__/script/train-events.lua:94: attempt to index local 'delivery' (a nil value)
stack traceback:
	__LogisticTrainNetwork__/script/train-events.lua:94: in function 'TrainArrives'
	__LogisticTrainNetwork__/script/train-events.lua:278: in function <__LogisticTrainNetwork__/script/train-events.lua:274>

I have a savegame where I can reproduce it, can be provided on request.

**Comment by Yousei9** [comment] 2020-08-28 15:58
duplicate of #226

**Closed by Yousei9** 2020-08-28 15:58 UTC
Labels: bug
