### ISSUE TITLE
LTN Wrong error message missing cargo

### ISSUE THREAD

**Issue by sebbi08** [Yousei9/Logistic-Train-Network#265] opened 2021-06-08 14:52 UTC
**Error message or bug description** 
Error message missing cargo offset by the created delivery.

Sometimes i get an error of missing cargo as you can see in the second image

![image](https://user-images.githubusercontent.com/9070136/121206560-daf43400-c878-11eb-9d88-cf6bce0a8f49.png)
![image](https://user-images.githubusercontent.com/9070136/121206504-d0399f00-c878-11eb-8e8c-c41dc86f79ac.png)

in the first image you can see that the content of the stop output is 2003 and in the second image the error for missing cargo because it expected 2013

the initial message for the created delivery also stated 2003

**To Reproduce**  

**LTN version**  
1.16.0

**Log file**  
Your factorio-current.log file. It is located in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by Yousei9** [comment] 2021-06-08 14:54
Looks like a duplicate of #252 to me

**Closed** 2021-06-08 14:59 UTC
Labels: bug

**Comment by sebbi08** [comment] 2021-06-08 15:04
Na i think this is a problem with the LTN manager as the error os only visible there and not in console nor in the allert on the bottom right
