### ISSUE TITLE
Error after Upgrade to 1.12.3 or 1.12.4

### ISSUE THREAD

**Issue by marr75** [Yousei9/Logistic-Train-Network#208] opened 2020-03-03 03:03 UTC
I encounter an error after updating that may have to do with the reported refactor. Log below.

```
 140.943 Error MainLoop.cpp:1202: Exception at tick 9766605: The mod LTN - Logistic Train Network (1.12.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_train_changed_state (ID 23)
The mod LTN Tracker (0.10.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Tracker::Custom event (ID 314)
__LTN_Tracker__/script/data_processing.lua:483: attempt to index local 'delivery' (a nil value)
stack traceback:
	__LTN_Tracker__/script/data_processing.lua:483: in function <__LTN_Tracker__/script/data_processing.lua:476>
stack traceback:
	__LogisticTrainNetwork__/script/train-events.lua:164: in function 'TrainLeaves'
	__LogisticTrainNetwork__/script/train-events.lua:201: in function <__LogisticTrainNetwork__/script/train-events.lua:195>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/train-events.lua:164: in function 'TrainLeaves'
	__LogisticTrainNetwork__/script/train-events.lua:201: in function <__LogisticTrainNetwork__/script/train-events.lua:195>
```

**Comment by raiguard** [comment] 2020-03-03 07:06
This is an error in LTN Tracker, not LTN itself. Some API changes were made that breaks LTNT. You'll need to modify your local copy of LTNT to conform to the changes.

**Comment by Yousei9** [comment] 2020-03-03 12:09
Duplicate of #207 and https://forums.factorio.com/viewtopic.php?f=214&t=81561

**Closed by Yousei9** 2020-03-03 12:09 UTC
Labels: not a bug
