### ISSUE TITLE
LTN Depot Load Balancing Issue

### ISSUE THREAD

**Issue by mohsenrf** [Yousei9/Logistic-Train-Network#242] opened 2020-12-18 11:40 UTC
Conditions:
1- A huge number of LTN Depots (in one location)
2- A huge stacker behind all depots
3- lots of trains in action

Current behavior:
1- Instead of utilizing all depots right away, most of the trains get stuck in the stacker waiting for a closer station to become available while there are lots of depots available (but a few blocks farther than the one train is waiting for).
2- Train changes its destination after a few seconds but never selects a depot that is a bit more distant. instead it sits in the stacker and constantly checks on the filled stations.

Expected behavior: 
- Train (LTN scheduler) should intelligently does a load balancing (a trade off between distance and traffic) so all the empty depots get utilized.

![Screen Shot 2020-12-18 at 2 42 14 PM](https://user-images.githubusercontent.com/4361224/102610828-153f0d00-4143-11eb-8e4f-475a56c727dc.png)

![Screen Shot 2020-12-18 at 2 42 16 PM](https://user-images.githubusercontent.com/4361224/102610953-51726d80-4143-11eb-8465-38b814b2d9ce.png)

**Comment by Yousei9** [comment] 2020-12-18 11:42
Duplicate of old post: https://forums.factorio.com/viewtopic.php?f=214&t=84802
Not a bug. That's just vanilla train behavior.

**Closed by Yousei9** 2020-12-18 11:42 UTC
Labels: bug

**Comment by mohsenrf** [comment] 2020-12-18 14:25
@Yousei9  Thank you. Giving stations unique names resolved the problem.
