### ISSUE TITLE
Add option to hide rich-text' actual text.

### ISSUE THREAD

**Issue by an-accident** [Yousei9/Logistic-Train-Network#254] opened 2021-02-22 15:43 UTC
Hi! Got an enchancement proposition.
I'm using icons for names of most of my train stations but it becomes very inconvienient when reading warning/error messages beacause every icon is followed by it's textual description (which does the opposite of being informantive since I memorize my station names by these icons and the additional text kind of breaks the point quick referencing them).
![Zrzut ekranu (599)](https://user-images.githubusercontent.com/48416874/108731160-909ab180-752c-11eb-9744-45a6d473b8ab.png)
I propose to add an option to hide the text (at least in the cases when used in station names).

**Comment by Yousei9** [comment] 2021-02-22 16:02
Duplicate of this forum thread: https://forums.factorio.com/viewtopic.php?f=214&t=82823

**Closed by Yousei9** 2021-02-22 16:02 UTC
Labels: enhancement
