### ISSUE TITLE
game crashes when train with fluid wagons arrive at LTN depot station in 0.16.7

### ISSUE THREAD

**Issue by marcus-no** [Yousei9/Logistic-Train-Network#87] opened 2017-12-26 22:31 UTC
16152.884 Script @__LogisticTrainNetwork__/control.lua:367: (TrainLeaves) train.id:162 wasn't found in global.StoppedTrains
16200.334 Script @__LogisticTrainNetwork__/control.lua:367: (TrainLeaves) train.id:162 wasn't found in global.StoppedTrains
16230.338 Script @__LogisticTrainNetwork__/control.lua:367: (TrainLeaves) train.id:162 wasn't found in global.StoppedTrains
16264.997 Script @__LogisticTrainNetwork__/control.lua:367: (TrainLeaves) train.id:162 wasn't found in global.StoppedTrains
16316.076 Script @__LogisticTrainNetwork__/control.lua:367: (TrainLeaves) train.id:162 wasn't found in global.StoppedTrains
16344.599 Script @__LogisticTrainNetwork__/control.lua:367: (TrainLeaves) train.id:162 wasn't found in global.StoppedTrains
16379.506 Script @__LogisticTrainNetwork__/control.lua:367: (TrainLeaves) train.id:162 wasn't found in global.StoppedTrains
16380.286 Error MainLoop.cpp:1013: Exception at tick 19137085: Error while running event LogisticTrainNetwork::on_train_changed_state (ID 23)
Passed index is out of range.
stack traceback:
        __LogisticTrainNetwork__/control.lua:1746: in function 'getWagonCapacity'
        __LogisticTrainNetwork__/control.lua:1761: in function 'GetTrainCapacity'
        __LogisticTrainNetwork__/control.lua:343: in function 'TrainArrives'
        __LogisticTrainNetwork__/control.lua:459: in function <__LogisticTrainNetwork__/control.lua:456>
16380.286 Error ServerMultiplayerManager.cpp:95: MultiplayerManager failed: "Error while running event LogisticTrainNetwork::on_train_changed_state (ID 23)
Passed index is out of range.
stack traceback:
        __LogisticTrainNetwork__/control.lua:1746: in function 'getWagonCapacity'
        __LogisticTrainNetwork__/control.lua:1761: in function 'GetTrainCapacity'
        __LogisticTrainNetwork__/control.lua:343: in function 'TrainArrives'
        __LogisticTrainNetwork__/control.lua:459: in function <__LogisticTrainNetwork__/control.lua:456>"
16380.286 Info ServerMultiplayerManager.cpp:696: mapTick(19137085) changing state from(InGame) to(Failed)
16380.300 Info GlobalContext.cpp:661: Waiting for child processes to exit:
16380.583 Info ServerMultiplayerManager.cpp:141: Quitting multiplayer connection.
16380.583 Info ServerMultiplayerManager.cpp:696: mapTick(4294967295) changing state from(Failed) to(Closed)
16380.585 Info UDPSocket.cpp:206: Closing socket
16380.586 Info UDPSocket.cpp:236: Socket closed

**Comment by Yousei9** [comment] 2017-12-27 07:27
Duplicate of #86

**Closed by Yousei9** 2017-12-27 07:27 UTC
Labels: duplicate
